### ISSUE TITLE
highlight messages in chat that contain your @username

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#1015]
Make it easier to notice if someone is chatting to you

**Comment by dudethatbe** [comment]
I saw this helper being used in the ChatMessage and thought it might be a good starting point. template https://github.com/datafruits/datafruits/blob/main/app/helpers/format-message-body.js#L7 
Can't figure out how to access the "this.currentUser" that's being referenced in the ChatMessage template, but of course it's javascript and this isn't always _this_

**Comment by dudethatbe** [comment]
![image](https://user-images.githubusercontent.com/2829501/210688657-ddaaafc6-f0b9-40ac-aff1-063befa1e860.png)
Ok this is super hacky, but I  added this if/else to the chat-message.hbs template
```
  <span class="mr-2" data-test-username>
    <Chat::Username
      @dontShowPopup={{true}}
      @role={{@message.role}}
      @style={{@message.style}}
      @pronouns={{@message.pronouns}}
      @username={{@message.user}}
      @avatarUrl={{@message.avatarUrl}}
      />
  </span>
  {{#if @message.hasMention}}
    <span class="bg-red" data-test-message-body>
      {{format-message-body @message.body}}
    </span>
  {{else}}
    <span class="" data-test-message-body>
      {{format-message-body @message.body}}
    </span>
  {{/if}}
```

**Comment by mcfiredrill** [comment]
added in https://github.com/datafruits/datafruits/pull/1023
