### ISSUE TITLE
high level users should be able to access photobooth

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#1049]
Maybe it could be inside the emoji selector?

**Comment by dudethatbe** [comment]
@mcfiredrill going through old issues and wondering about this one. seems easy to show the button if they have a certain level..
seems like there should be some actual authentication going on the photobooth app though 🔐 started looking at this old code on glitch and thinking about how we can do that

**Comment by dudethatbe** [comment]
copied just enough code over to get the interface to work. still needs a lot of work as far as image uploading and connecting to the chat goes
![image](https://user-images.githubusercontent.com/2829501/230760884-5da6c321-56b4-410d-a23f-b3bfbdab40bb.png)

**Comment by mcfiredrill** [comment]
Nice ! 

> actual authentication going on the photobooth app though

I think we could check for a user token through hotdog lounge for this.

**Comment by dudethatbe** [comment]
i was thinking the option to show the camera menu would only need to be rendered when the user has a hit a certain level. should that be enough? maybe some type of verification before they send the photo?

**Comment by mcfiredrill** [comment]
Got a PR for this I can take a look at ? @dudethatbe

**Comment by mcfiredrill** [comment]
>  i was thinking the option to show the camera menu would only need to be rendered when the user has a hit a certain level. should that be enough? maybe some type of verification before they send the photo?

That should be fine and we will do another verification on the hotdog lounge backend before the photo actually gets sent.
