### ISSUE TITLE
autolink URLs in forum posts and wiki pages

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#1061]
Chat messages will turn a link into an <a> tag automatically.
It would be nice if forum posts and wiki pages had the same behaviour.

Chat messages do it with this helper using the `autolink` function from autolink-js package.
https://github.com/datafruits/datafruits/blob/main/app/helpers/format-message-body.js#L9

Forum posts/wiki pages should be able to do the same.

**Comment by dudethatbe** [comment]
thanks for reminding me about the helpers @mcfiredrill

**Comment by dudethatbe** [comment]
found out there's settings in the markdown options to do this already. next step: refactor the chat to use the same markdown
