### ISSUE TITLE
update edit user settings

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#1088]
The page with all the controls to update your settings is getting a little chunky. The white text on the pink background is not a good contrast. The Time Zone select doesn't have any CSS styling associated with it yet. Some other things can probably be done to make it a little easier to understand what's going on. Open to suggestions

**Comment by mcfiredrill** [comment]
![Screenshot 2023-03-17 at 1 28 39 PM](https://user-images.githubusercontent.com/66243/226032039-9c34f185-fd9c-4121-9381-1163eb76361d.png)
