### ISSUE TITLE
accept image data

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#1109]
sure would be cool to copy and paste some image data into the chat instead of only being able to use a URL
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URLs

**Comment by mcfiredrill** [comment]
I'd check out the clipboard API https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

https://levelup.gitconnected.com/how-to-copy-or-paste-image-by-plain-javascript-6ea804c6944a
