### ISSUE TITLE
implement our own form instead of using google forms for dj-inquiry

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#118]
This way we can translate it etc....

**Comment by slaponicus** [comment]
https://formspree.io/ is super easy to set up - would something like this work? that way we could do whatever we needed to the front-end (i.e. translate) without worrying about sendmail or saving the entry somewhere.

**Comment by mcfiredrill** [comment]
There are two main motivations for this:

* I want to be able style the form to match the rest of the site, not sure if google forms allows this
* I want to integrate the form directly with the back end, so I could create the new DJs account with preferably just one 

So I imagine it might be easier to just roll our own 🤔

**Comment by mcfiredrill** [comment]
closed in https://github.com/datafruits/datafruits/pull/135
