### ISSUE TITLE
404 pages

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#133]
Add/style a 404 page
Doesn't seem to work correctly now:
http://www.datafruits.fm/asdf

**Comment by slaponicus** [comment]
Added one in #187 but couldn't figure out how to get the wildcard route to work with the menu and player. At least it's a start!

**Comment by mcfiredrill** [comment]
> the wildcard route to work with the menu and player. 

Seems like its working, whats the issue exactly?

**Comment by slaponicus** [comment]
I was just thinking that it would be nice to render the wildcard route with the menu and player (like all of the other routes) - that way if someone accidentally went to a non-existent page, their listening experience wouldn't be interrupted and they would be able to navigate to a real page via the menu.

**Comment by mcfiredrill** [comment]
Ah I get it...I'll see if I can do that!

**Comment by mcfiredrill** [comment]
I think this is done, was their anything else to do?

**Comment by sharpshark28** [comment]
404 page has been working for me fwiw :)
