### ISSUE TITLE
Video player is playing audio form input, with no option to mute

### ISSUE THREAD

**Issue by fastdrums** [datafruits/datafruits#185]
just need to update player to:

{{#if videoStreamActive}}
<video id="video-player" class="video-js vjs-default-skin vjs-16-9 vjs-big-play-centered" controls muted preload="auto" data-setup='{"fluid": true}'>
  <p class="vjs-no-js">
    To view this video please enable JavaScript, and consider upgrading to a web browser that
    <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
  </p>
</video>
{{/if}}

**Comment by fastdrums** [comment]
LOL it parsed my html, need to add 'muted' property to video tag

**Comment by mcfiredrill** [comment]
The video is muted now I'm pretty sure. Closing.
