### ISSUE TITLE
datafruits-volume not loading

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#196]
If you press play after setting the volume to something other than 0.8, it will default to the volume 0.8

**Comment by mcfiredrill** [comment]
Probably fixed if we set the volume in didInsertElement
https://github.com/datafruits/datafruits/blob/master/app/components/datafruits-player.js#L132

**Comment by mcfiredrill** [comment]
fixed in https://github.com/datafruits/datafruits/commit/e7920bcf3496eb6a6fd01b93ee8125caa5342a81
