### ISSUE TITLE
replace emojione

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#20]
If there was something that just used the normal system emoji images, with fallback to images, I think it would be better.

**Comment by dudethatbe** [comment]
how do we still feel about this? i think it adds to odd appeal of the site that we have some outdated emoji set that no one uses anymore. If anything, I'd like to have an emoji selection menu that displays all of these (like in discord or other chat dealies)

**Comment by mcfiredrill** [comment]
I'm not sure how I feel, it does feel kind of part of the site now that its been around so long.

If there's any bugs in it I'm not sure how we will upgrade, I forked it a long time ago to add custom emoji and haven't incorporated any upstream changes since.
https://github.com/mcfiredrill/emojione#animated-emoji

I guess the project isn't even called emojione anymore.
https://emojipedia.org/joypixels/

**Comment by dudethatbe** [comment]
If there were any serious bugs in it, I'd think they would have surfaced by now. Maybe something will break in the future, but it seems to me that it has been working just fine. I'd be inclined to close this and revisit the issue if emojione causes any issues.

**Comment by mcfiredrill** [comment]
Sounds good to me
