### ISSUE TITLE
mixcloud link appears even if track has not been uploaded to mixcloud 

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#277]
![mixcloud](https://user-images.githubusercontent.com/66243/68922188-55a0be80-07be-11ea-9506-5296f2471f3d.JPG)

This might need to be fixed on the API side as well.

**Comment by dudethatbe** [comment]
Turns out this mostly because of how streampusher is returning the links to mixcloud uploads https://github.com/streampusher/api/blob/6c2f7e9ff0391ed5e90636aec46500354b52e9d3/app/serializers/playlist_track_serializer.rb#L16
