### ISSUE TITLE
use stop button instead of pause button on live stream

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#287]
Currently you can pause the live stream, and play back. This is kind of unreliable as you can end up several seconds or minutes behind of the actual live stream.

Usually you just want to reload the stream and start it playing again anyway, so it would be better if it just 'reloaded' the stream again instead of pausing it, so you don't have to worry about reloading it manually to catch up to the current time.

So there are two parts to this:

* change the pause icon to a stop icon (playing back podcasts should still pause!)
* change the behavior to stop and reload the stream instead of pausing

**Comment by sharpshark28** [comment]
What's the difference between the `components/datafruits-player` and the `components/container/datafruits-player`?

**Comment by mcfiredrill** [comment]
`container` is used for the mini player that is embedded in tweets, by using some special meta tags.
It basically renders a mini version of the site that only contains the player.
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/player-card

It can be tested here:
https://cards-dev.twitter.com/validator
