### ISSUE TITLE
refactor to use tailwind css

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#288]
https://tailwindcss.com/

This guide is pretty good.
https://github.com/chrism/emberjs-tailwind-purgecss

**Comment by sharpshark28** [comment]
Love tailwind, can probably close #5 if the intent is to refactor to tailwind.

Happy to contribute if this gets started.

**Comment by mcfiredrill** [comment]
I think the main issue I was having is an addon we use , [ember-calendar](https://github.com/mcfiredrill/ember-calendar), (my fork of it, specifically) uses sass and it was difficult to use ember-cli-sass with the method of using tailwind above.

I think I found some sort of workaround, it would be nice if that addon didn't depend on sass however.
