### ISSUE TITLE
replace google analytics with something else

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#293]

**Comment by nikolas** [comment]
[GoatCounter](https://www.goatcounter.com/) might be a good option.. i haven't used it.

**Comment by mcfiredrill** [comment]
I haven't contacted them but GoatCounter seems like the author wouldn't mind us using the free plan , as datafruits is open source. I'm not sure it will work with our setup though, it just works by including a script tag which might not work with fastboot.

Matomo might work but looks like they don't have a free plan.

**Comment by mcfiredrill** [comment]
To be honest I feel like I don't really care about metrics right now? I haven't checked google analytics in ages.

The only case I can think of where I would really need it is if I got some unexpected traffic that caused some outages and I needed to check it out. Even if that were so, I can check the traffic metrics on heroku, even though I can't see the exact number of visitors.
