### ISSUE TITLE
[QUEST] get the test suite passing! 

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#294]
This is a quest issue to get the test suite passing and working reliably.

If you'd like to tackle any of the tests, leave a comment!

- [ ] acceptance tests
  - [ ] chat (how to mock the pheonix server responses?)
  - [ ] timetable
  - [ ] podcasts
  - [ ] blog 
  - [ ] djs
  - [ ] dj inquiry form
- [ ] component tests
  - [ ] blog-post.js
  - [ ] blog-post-preview.js
  - [ ] chat-lazy-image.js
  - [ ] chat-message.js
  - [ ] chat-messages.js
  - [ ] container/datafruits-player.js
  - [ ] datafruits-chat-input-message.js
  - [ ] datafruits-chat.js
  - [ ] datafruits-player.js
  - [ ] datafruits-visuals.js
  - [ ] giphy-loader.js
  - [ ] giphy-search.js
  - [ ] locale-selector.js
  - [ ] network-status.js
  - [ ] notifications.js
  - [ ] podcasts-loader.js
  - [ ] podcasts-search.js
  - [ ] podcast-track.js
  - [ ] timetable-calendar.js
  - [ ] timetable-loader.js
  - [ ] tweet-button.js
  - [ ] user-list-item.js
  - [ ] window-resize-handler.js
- [ ] unit tests
    - [ ] services
    - [ ] models
- [x] js lint https://github.com/datafruits/datafruits/pull/301
- [x] template linting https://github.com/datafruits/datafruits/pull/291

**Comment by sharpshark28** [comment]
Oooo nice! I'll keep an eye on this issue and comment if I'm working on a checklist item.

**Comment by sharpshark28** [comment]
Just a (somewhat controversial) thought, in the past when I've been on projects with a red build and a lengthy list of TODO's to get it green we've culled all failing tests and made plans to increase coverage later. It may seem sad to lose tests, but it can be argued that they are dead (unmaintained and failing) tests that are holding back other work from being reliably checked by failing the builds. 

So my suggestion is doing a quick passover to see if any tests can be fixed easily (5 min each at most) and if not then we just cull them and then use this list in another issue to increase test coverage after the project is green.

**Comment by sharpshark28** [comment]
Starting to poke at fixing some failing tests as I find time https://github.com/datafruits/datafruits/pull/295

Anyone can feel free to commit a few fixes as they can.

**Comment by mcfiredrill** [comment]
> Just a (somewhat controversial) thought, in the past when I've been on projects with a red build and a lengthy list of TODO's to get it green we've culled all failing tests and made plans to increase coverage later. It may seem sad to lose tests, but it can be argued that they are dead (unmaintained and failing) tests that are holding back other work from being reliably checked by failing the builds.

Good point I definitely agree. Any green build with less than 100% coverage is definitely better than none at all. I'm hoping to use this issue to just get the build passing again, then work on getting more coverage if needed later.

**Comment by dfridkin** [comment]
Hey! Got here from the snailzone stream -- very interested in helping support the project! I forked the project, I'll start digging in now :)

**Comment by mcfiredrill** [comment]
Welcome! Feel free to reach out if you have any questions. @dfridkin 
If you were thinking of working on this issue, we have *some* tests now but its always nice to have more.

**Comment by dfridkin** [comment]
Could you open a new issue that has an updated checklist and close this one? I figured I'd start here because it's a good way to learn the setup of the project, but if there's a more pressing issue I'd be happy to take a look at that as well. Thanks for the warm welcome!

**Comment by mcfiredrill** [comment]
@dfridkin 
I will try to update this checklist tomorrow! I know for sure we don't have any acceptance tests yet.

In the meantime, you may also want to check out the issues with the "good first issue" and "good for new contributors" labels.
https://github.com/datafruits/datafruits/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22
