### ISSUE TITLE
mute the audio on the visuals to allow autoplay

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#297]
According to chrome's policy, 
https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
the video should autoplay if the audio is muted.
(There shouldn't be any audio coming through the visuals anyway, the icecast stream is used for that)

**Comment by mcfiredrill** [comment]
probably need to a player.mute() or something here
https://github.com/datafruits/datafruits/blob/2f175b04bbbd555d85c324ef3e3f28eb0be7bf01/app/services/video-stream.js#L50

**Comment by sharpshark28** [comment]
Relates to #170

**Comment by mcfiredrill** [comment]
> Relates to #170

Yep this may fix the mobile issue....

**Comment by mcfiredrill** [comment]
I noticed the video has the `muted` attribute in the template anyway... https://github.com/datafruits/datafruits/blob/master/app/templates/components/datafruits-visuals.hbs#L8
