### ISSUE TITLE
Replace ember-i18n (deprecated) with ember-intl

### ISSUE THREAD

**Issue by hergaiety** [datafruits/datafruits#326]
ember-i18n is deprecated and should be replaced with ember-intl. Performing this upgrade should clear the ember build warning, keep the project green and potentially fix some npm audit warnings.

There's a migration tool supposedly https://github.com/DockYard/ember-i18n-to-intl-migrator

**Comment by mcfiredrill** [comment]
Sounds good, I think I looked into this briefly before. I will give that migrator a try.
