### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by katktv** [datafruits/datafruits#342]
Looking at the repository itself it isn't immediately obvious that the license of this project is MIT, so this has to have a LICENSE file for GitHub to pick it up and clear up the confusion. 

[Example](https://github.com/github/choosealicense.com/blob/gh-pages/LICENSE.md) of a license.

**Comment by mcfiredrill** [comment]
Closed in https://github.com/datafruits/datafruits/pull/519
