### ISSUE TITLE
support base64 images in chat

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#348]
If  you paste a base64 url for an image, it just gets displayed as text.

While its pretty funny bug, it doesn't seem too hard to just detect if a message has a base64 image in it and just display it in an <img> tag.

**Comment by dudethatbe** [comment]
only took 3 years ✔

**Comment by mcfiredrill** [comment]
![](https://media.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif)
