### ISSUE TITLE
Volume slider remains open

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#350]
The control to adjust the audio volume on the frontend isn't exactly working as expected. Hovering over the control reveals the slider, and moving the mouse away from it will keep it open. If you move the mouse back near the control, it will eventually collapse and the volume slider will no longer be showing. I'm sure we're trying to avoid requiring a mouse click to expand/collapse it, since that either mutes/unmutes the audio.
I've attached a gif that shows what I'm trying to explain here. No mouse clicks taken place, all hovering. You can see that the first attempt to close the player didn't work because it got too close and expanded the volume control back to display
![1586482840249](https://user-images.githubusercontent.com/2829501/78954688-dbddda00-7aaa-11ea-84a8-85890b35e883.gif)

**Comment by bradwbradw** [comment]
should be fixed in https://github.com/datafruits/datafruits/pull/380
