### ISSUE TITLE
Fix site subnav appearing then disappearing when hover over “Radio”

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#378]
maybe adjust code here

https://github.com/datafruits/datafruits/blob/7d9115acbbda8aa8a873dc794fd5fa29e2436a85/app/controllers/home.js#L41

**Comment by mcfiredrill** [comment]
related https://github.com/datafruits/datafruits/issues/350

**Comment by bradwbradw** [comment]
should be fixed in https://github.com/datafruits/datafruits/pull/380
