### ISSUE TITLE
tab completion in chat

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#404]
Would be great to tab complete emoji, usernames. I thought it was working before but it isn't now.

<bountysource-plugin>

**Comment by dfridkin** [comment]
I did a little digging and I think I found the source of the issue [here -- see lines 124-138](https://github.com/datafruits/datafruits/compare/master...dfridkin:tab-completion#diff-0555ae6ec08906732b492b45eb6ea79eR124-R138). I don't want to test this too much more because I'm spamming the chat :(

**Comment by mcfiredrill** [comment]
Ah ok that looks sus....my first thought is does it work again if we delete that?

**Comment by dfridkin** [comment]
Sorry, the commit is unclear -- I *just* wrote that `on('keydown'` block, it wasn't working before that was added either.

**Comment by mcfiredrill** [comment]
Ah lol my bad sorry.
It does look like the right approach, but in ember you can write action handlers directly on components.
You may want to extract that element `input-message` to its own component (if its not already) and write a handler for `keyUp`
https://guides.emberjs.com/v2.0.0/components/handling-events/#toc_event-names

**Comment by mcfiredrill** [comment]
Will be addressed in https://github.com/datafruits/datafruits/issues/457
