### ISSUE TITLE
djs/show page is really slow

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#444]
https://datafruits.fm/djs/tchan

Check out the network requests, XHR page. Seems there is a request for each track, maybe each tag too? Just way too many requests happening...

This may need to be fixed on [streampusher/api ](github.com/streampusher/api) side but making an issue here anyway.

**Comment by mcfiredrill** [comment]
related https://github.com/datafruits/streampusher-api/issues/54

**Comment by dudethatbe** [comment]
can this be closed @mcfiredrill ?

**Comment by mcfiredrill** [comment]
Yeah this page works better now
