### ISSUE TITLE
[QUEST] accessibility 

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#449]
Taking the tips from the lighthouse report.

## names and labels
- [x] labels for buttons
    - [x] span.jp-volume-controls
- [x] Form elements do not have associated labels
    - [x] chat message input
    - [x] locale selector
- [x] Links do not have a discernible name

## contrast
- [ ] Background and foreground colors do not have a sufficient contrast ratio.
  maybe this feature could help https://github.com/datafruits/datafruits/issues/289

## best practices
- [x] `[id]` attributes on the page are not unique
- [x] `[user-scalable="no"]` is used in the `<meta name="viewport">` element or the `[maximum-scale]` attribute is less than 5.

## internationalization
- [x] `<html>` element does not have a [lang] attribute

## tables and lists
- [x] Lists do not contain only `<li>` elements and script supporting elements (`<script>` and `<template>`).
- [x] List items `(<li>)` are not contained within `<ul>` or `<ol>` parent elements.

## navigation
- [x] Some elements have a [tabindex] value greater than 0

**Comment by mcfiredrill** [comment]
>  <html> element does not have a [lang] attribute

This is supposed to be a feature of `ember-intl`, so it should just be a matter of configuring that to work.
https://github.com/ember-intl/ember-intl/pull/649/files

**Comment by mcfiredrill** [comment]
I checked in the console
`$("html").lang`
`en-us`
So it seems to be working, its probably just set with JS in a way the lighthouse tool cannot detect I guess. :shrug:

**Comment by dudethatbe** [comment]
making changes in this branch https://github.com/datafruits/datafruits/tree/449-accessibility

**Comment by mcfiredrill** [comment]
> making changes in this branch https://github.com/datafruits/datafruits/tree/449-accessibility

@dudethatbe 
This looks awesome, do you mind opening a draft WIP PR for this? Easier to comment that way...

**Comment by mcfiredrill** [comment]
I'd also like to look into using these addons from [ember-a11y](https://github.com/ember-a11y).

https://github.com/ember-a11y/a11y-announcer
This seems pretty important, without this it seems like screen readers have no idea the current URL changed.

https://github.com/ember-a11y/ember-a11y-testing
Seems to run some accessibility tests, not sure how they differ from the lighthouse reports though.

https://github.com/ember-a11y/ember-a11y-landmarks
This seems like it may make it easier to add `roles` in landmark elements.
