### ISSUE TITLE
make the images on shows page bigger

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#459]
The images on shows page are really small.
https://datafruits.fm/shows/429556

They could be really big, like on KPISS:
https://kpiss.fm/show/extra-anchovies/

**Comment by 4lp** [comment]
I'll play around with this and see if I can come up with a new design

**Comment by mcfiredrill** [comment]
> I'll play around with this and see if I can come up with a new design


@4lp excellent! Go for it try out anything go crazy. :)

**Comment by 4lp** [comment]
Here are a couple of ideas I've been playing with:

Tiled show poster
![Idea 1](https://i.imgur.com/w1v8MUZ.png)
Full width zoomed show poster
![Idea2](https://i.imgur.com/T6E9xmF.png)

Thoughts/opinions? I'm happy to change this entirely if y'all don't think it looks good 

Also, the fruit emoji is random every time 😋

**Comment by 4lp** [comment]
Pushed my first attempt in #545

**Comment by dudethatbe** [comment]
Looks great @4lp ! I would probably go for the tiled design since most flyer images contain text in them. It would be nice if the host of the show could specify their banner design (full-width or tiled), but that would require some streampusher changes of course @mcfiredrill .
