### ISSUE TITLE
switching back to english breaks the site

### ISSUE THREAD

**Issue by novadeviator** [datafruits/datafruits#490]
If you switch to some other language (espaniol for example) and then back to english, all the possible translated words become "missing translation xxxx.xxxx for locale en-us"

![Screenshot from 2020-08-15 12-18-05](https://user-images.githubusercontent.com/744626/90310452-a7af7580-def1-11ea-8465-b5cd8f6f6e1e.png)

**Comment by mcfiredrill** [comment]
Hi, Thank you for the issue!

I think I've resolved this issue here. 
https://github.com/datafruits/datafruits/commit/7b952254e7deb09f90cc3fd8a53fc6db1479379d
Can you confirm it still happens? You might have to hard refresh to get the latest code changes.

**Comment by mcfiredrill** [comment]
Going to assume this is fixed...please reopen if its still an issue!
