### ISSUE TITLE
Move runtime dependencies to "dependencies" instead of "devDependencies"

### ISSUE THREAD

**Issue by caass** [datafruits/datafruits#493]
I'm currently working on dockerizing the site so it'll work with Kubernetes. Part of this process is trying to keep the image as small as possible. Currently, all of the dependencies required to *run* and to *develop* datafruits are listed under `devDependencies` in package.json. This means that if we want to run fastboot, we need to install everything listed under `devDependencies`. Eventually, someone should try and move all of the runtime dependencies (e.g. `moment`, `emojione`) to `dependencies` so that we can build the docker image without it being humongous. The issue is that a lot of the dependencies aren't installed directly, like we use `ember-moment` instead of `moment`, but at runtime fastboot needs `moment`.

**Comment by caassandra** [comment]
![image](https://user-images.githubusercontent.com/25358963/90697396-4e767780-e24c-11ea-9358-03d90ebb2ebe.png)
Currently we're at a pretty substantial 2GB, while the `alpine` base image is only a few hundred megabytes. It would be cool to get our application only a little bigger than that.

**Comment by caassandra** [comment]
Posting again to say i don't think this is the way forward -- I'm not sure what to do but I think it has to do with [this](https://github.com/ember-fastboot/ember-cli-fastboot#using-nodenpm-dependencies).

**Comment by mcfiredrill** [comment]
We stopped using fastboot for a bit unfortunately due to memory leaks ... :sweat: 
I'd like to get back on fastboot at some point, but I'm not sure if we'll be using docker for it or not, whatever is easiest. 
But as you said 

>  i don't think this is the way forward 

I'll be closing this for now.

Thanks again for your help <3
