### ISSUE TITLE
user settings page

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#522]
What settings should be on the user settings page?

* username 
* displayname
* avatar

* email / change password

**Comment by mcfiredrill** [comment]
I think it would be cool to have something like micromusic.net's "style" field.

It doesn't actually do anything, it's just kind of a funny, home-grown feel thing....

![styles](https://user-images.githubusercontent.com/66243/98492340-e5b30000-227a-11eb-9796-6fc99707b68e.gif)

**Comment by gloomsmusic** [comment]
Can one of the options be open Gangnam style??

**Comment by azaxy** [comment]
heres some:

perfect, cool, cold.... rude... gooey... unknown

**Comment by mcfiredrill** [comment]
ah yeah!!!!! @azaxy

**Comment by mcfiredrill** [comment]
related https://github.com/datafruits/streampusher-api/pull/45

**Comment by mcfiredrill** [comment]
WIP mockup design in figma
https://www.figma.com/file/3ZkvG1sAdiKkHKzUd4zXZV/datafruits-user-settings?node-id=0%3A1

**Comment by mcfiredrill** [comment]
We have a user settings page now
