### ISSUE TITLE
gif search scrolling

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#523]
when searching for gifs, the browser window doesn't appear to readjust to allow you to scroll down to see the rest of the search results. I feel like it worked fine after changing over to tailwind so maybe it's not related to that?

**Comment by dudethatbe** [comment]
actually it seems like you can't scroll up or down when the gif search is open

**Comment by mcfiredrill** [comment]
Thanks, I noticed that too. I have a redesign in mind for the gif selector anyway so I would probably prefer to focus efforts on that.
https://github.com/datafruits/datafruits/issues/457

**Comment by dudethatbe** [comment]
ah ok didn't realize, makes sense. I think most people are still using separate tabs to find gifs anyways
