### ISSUE TITLE
fix CoC CSS

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#524]

**Comment by dudethatbe** [comment]
I recently made some changes to the CoC here https://github.com/datafruits/datafruits/commit/23b30bc2809c1a0e9e401fb8481b6a7c95619b14 but I think there are still improvements to be made to the overall design of this page. The spacing between lines for the <p> elements could be increased a little bit. Could also reduce the width of these paragraphs to wrap earlier; Full-screen view of this page is not ideal. I've included an attachment of some rushed highlighting to show where I think the text should start wrapping around:
![image](https://user-images.githubusercontent.com/2829501/98160689-83d64d00-1eac-11eb-8843-6e366b7e6aee.png)
When the width of the page is about half then it looks pretty good

**Comment by mcfiredrill** [comment]
Changes here https://github.com/datafruits/datafruits/commit/23b30bc2809c1a0e9e401fb8481b6a7c95619b14 look good !

Rather then left aligning the text and wrapping, maybe adding padding/margins/flexbox on both sides and centering the text might be better  ? (This might need to be applied to other pages as well.)
