### ISSUE TITLE
investigate if we can remove moment.js dependency

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#540]
With native APIs advancing, we may not need to use moment.js anymore. Its a pretty big chunk of the bundle size, so it would be nice to remove it. 

https://github.com/opencollective/opencollective/issues/2446#issuecomment-692520142

The only thing I think we might need is timezone support, but really we only show times in the user's timezone, we aren't really converting between timezones, so there may be a way we can go without the huge moment-timezone package.
https://github.com/datafruits/datafruits/blob/1a1ac35aee7567caf90313448af4b2f91f314274/app/helpers/format-date.js#L7

Search and grepping for moment, we don't have too many places using it...
```
ag moment app 
app/controllers/home/timetable.js
4:import moment from 'moment';
8:    defaultValue: moment().format('YYYY-MM-DD'),

app/helpers/format-date.js
2:import moment from 'moment';
7:  var formattedTime = moment(time[0]).tz(timeZone.name()).format('MM-DD-YYYY dddd HH:mm z');

app/helpers/format-message-timestamp.js
2:import moment from 'moment';
5:  return moment(timestamp[0]).format('HH:mm:ss');

app/routes/home/index.js
6:import moment from 'moment';
15:      start: moment().format('YYYY-MM-DD'),
16:      end: moment().endOf('month').add(1, 'month').format('YYYY-MM-DD'),

app/models/dj.js
4:import moment from 'moment';
36:        return moment(scheduledShow.start).isSameOrAfter(Date.now());

app/components/timetable-loader.js
4:import moment from 'moment';
31:      query.start = moment(start).startOf('month').subtract(1, 'month').format('YYYY-MM-DD');
32:      query.end = moment(start).endOf('month').add(1, 'month').format('YYYY-MM-DD');
34:      query.start = moment(start).startOf('week').subtract(1, 'week').format('YYYY-MM-DD');
35:      query.end = moment(start).endOf('week').add(1, 'week').format('YYYY-MM-DD');
```

**Comment by 4lp** [comment]
Would it be enough to replace moment with [day.js](https://day.js.org/) or do you want to try and use the browser API first? I think replacing moment with day.js would be trivially easy since they have almost the same API. Happy to do this if you think it's a good idea : )

Alternatively, stripping out the locales from the moment package removes like 90% of the size iirc - that's another option we could try.

**Comment by mcfiredrill** [comment]
> Would it be enough to replace moment with day.js or do you want to try and use the browser API first? I think replacing moment with day.js would be trivially easy since they have almost the same API. Happy to do this if you think it's a good idea : )

> Alternatively, stripping out the locales from the moment package removes like 90% of the size iirc - that's another option we could try.

Either of these would be great...I haven't used day.js but it sounds like its the same API with a tenth of the size..so that would be great. I think the only thing I'm concerned about is I'm not sure if this code requires the massive timezone/locale(I am probably conflating two different concepts here) packages:
```
app/helpers/format-date.js
2:import moment from 'moment';
7:  var formattedTime = moment(time[0]).tz(timeZone.name()).format('MM-DD-YYYY dddd HH:mm z');
```

We could always move to using native browser APIs later if we switch to days.js.

**Comment by 4lp** [comment]
Done in #546
