### ISSUE TITLE
homepage css issues on safari

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#553]
Some flexbox issue going on with Safari on the home page. The posts are overlapping each other.

![safari_resize_df](https://user-images.githubusercontent.com/66243/101302511-1fc5f080-387f-11eb-8b4e-4efa92d43119.gif)

**Comment by agkosd** [comment]
I could give it a try!

**Comment by mcfiredrill** [comment]
Hi @agkosd feel free to give it a shot!
The code for this template is here:
https://github.com/datafruits/datafruits/blob/master/app/templates/home/index.hbs

Let me know if I can help with anything. It should be easy to solve if you are familiar with tailwind, I think.

**Comment by nresh** [comment]
@mcfiredrill I tried to replicate this behavior on Safari (v 14.1.1), but the flexbox seems to be working properly, with no overlap.  this may not be a relevant issue anymore

**Comment by mcfiredrill** [comment]
Yeah I'm pretty sure this is fixed now, thanks for checking it out. @nresh 
Closing
