### ISSUE TITLE
vol control looks a bit wonky now with the theme selector added

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#567]
![vol_control_issue](https://user-images.githubusercontent.com/66243/102852076-c2c26100-4460-11eb-8d11-43077d992bee.gif)

**Comment by nresh** [comment]
@mcfiredrill this is what it looks like now:

<img width="340" alt="Screen Shot 2021-07-12 at 10 58 56 PM" src="https://user-images.githubusercontent.com/9378055/125398900-bf42e880-e364-11eb-873a-0053b66cb865.png">

is this still wonky?  I'm not sure how it's supposed to look, so not sure whether this is a real issue

**Comment by dudethatbe** [comment]
extremely late response, but thanks for confirming it doesn't look like that anymore. I can confirm it looks fine on desktop/mobile now.
