### ISSUE TITLE
wrong logo showing on mobile

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#569]
The 'datafruitsfm' at top should be hidden at the top at this screen size. ![image](https://user-images.githubusercontent.com/66243/103058777-8ae52600-45e6-11eb-8f26-5c648af4d724.png)

Only the logo image should be shown.

**Comment by nresh** [comment]
@mcfiredrill could not reproduce this one either. one thing I did notice is that you can't see the theme selection on mobile (not sure if that's by design):

![IMG_3651](https://user-images.githubusercontent.com/9378055/125400097-53617f80-e366-11eb-9764-9511fde24513.PNG)

**Comment by mcfiredrill** [comment]
Seems fixed now
