### ISSUE TITLE
Update Donate

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#694]
The _DONATE_ button on the site has been helpful, but could use some improvements to make it more clear how it works. On the forum we had discussed a few options on how tipping the dj should work, but we should make a dialog appear when clicking on the _DONATE_ button instead of opening an arbitrary link set on the back-end. 
The modal should have a clear title stating that they are about to tip money to the performer
Below the title we can add our ideas from the earlier discussion (exclusive fruit animations, merchandise, patreon). I think be dependent on the fruit-tipping to be implemented. Then at the bottom there should be a _CHECKOUT_ type of option that has a Paypal (boo), CC (stripe or something?), or however else we plan on accepting payments.
```
┌────────────────────┐
│ U ARE ABOUT TO TIP │
│ * currentDJ        │
│- - - - - - - - - - │
│ TIPPING OPTIONS    │
│ * RARE ANANAS $8   │
│ - - - - - - - - - -│
│                    │
│ checkout w/        │
│  [paypal] [CC]     │
└────────────────────┘
```

**Comment by mcfiredrill** [comment]
I think the first version of this , before we implement the fruit tips, could look something like.
```
┌─────────────────────────────────────────────────────┐
 |  You can donate to the DJ here:
  |*dj's custom URL entered on streampusher*
|
 | Or you can also support us on patreon or with a one time donation on paypal.
  └────────────────────────────────────────────────────┘
```

Sorry I'm not good at ascii art ><

**Comment by rbxbx** [comment]
is there a canonical way of doing DF modals? Did some grepping around and mostly just found the login modal -- would using that as a starting point make sense or nah?

**Comment by mcfiredrill** [comment]
@rbxbx Absolutely! I was thinking just copying that modal's style pretty much verbatim would be fine :+1:

**Comment by mcfiredrill** [comment]
Fixed it https://github.com/datafruits/datafruits/pull/698 thanks @rbxbx  !
