### ISSUE TITLE
add info about our governance process

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#765]
We say in tweets and whatnot that we are run democratically by the community, but we don't actually really mention that on our website.

Perhaps we can add some more info, links on our about page? Maybe a link to the forum ?
https://datafruits.fm/about/

**Comment by dudethatbe** [comment]
Not to be overly presumptuous, but this is explained on the  [About page](https://www.datafruits.fm/about) . Feel free to re-open this if it's missing anything
