### ISSUE TITLE
alert box from broken image link

### ISSUE THREAD

**Issue by dudethatbe** [datafruits/datafruits#886]
a messagebox that says 'error' is broadcasted to all chat users at the same time. it's funny, but it'd be nice to fix this and find a better use for sending a message to the chat.
For some reason this image works:
https://cdn11.bigcommerce.com/s-3b5vpig99v/images/stencil/1280x1280/products/108893/863799/GruulGuildmage__40895.1648681726.jpg?c=2

but this one from twitter doesnt:
https://pbs.twimg.com/media/Dwf6HhDVAAAysz3.png

also the bug doesn't seem to appear on chrome (at least for me locally) and _does_ appear on firefox

**Comment by mcfiredrill** [comment]
I would start by at least changing this line to use console.log instead of alert https://github.com/datafruits/datafruits/blob/13ff7726b67cb1b471ad9d2c987cf75b172a9da8/app/components/chat-lazy-image.js#L13

**Comment by mcfiredrill** [comment]
This was fixed
