### ISSUE TITLE
wiki pages break if title has weird chars

### ISSUE THREAD

**Issue by mcfiredrill** [datafruits/datafruits#994]

**Comment by dudethatbe** [comment]
Any examples of which characters break this? I was looking at the Form code and I don't think it's doing anything to make the title text "safe" https://github.com/datafruits/datafruits/blob/main/app/components/wiki/form.ts#L32

I read the API page for htmlSafe and it seems to declare that a string is safe, not actually make it safe https://api.emberjs.com/ember/release/functions/@ember%2Ftemplate/htmlSafe

> A word of warning - The htmlSafe method does not make the string safe; it only tells the framework to treat the string as if it is safe to render as HTML. If a string contains user inputs or other untrusted data, you must sanitize the string before using the htmlSafe method. Otherwise your code is vulnerable to [Cross-Site Scripting](https://owasp.org/www-community/attacks/DOM_Based_XSS). There are many open source sanitization libraries to choose from, both for front end and server-side sanitization.

**Comment by dudethatbe** [comment]
@mcfiredrill  is this still an issue?

**Comment by mcfiredrill** [comment]
I think question marks were breaking it but it should be fine now
